const accountController = require("../../controller/client/account.controller")
const router = require("express").Router()
router.get("/login", accountController.login)
router.get("/register", accountController.register)
router.get("/setting", accountController.setting)
router.get("/setting/information", accountController.information)
router.get("/setting/reset-password", accountController.resetPassword)
router.get("/setting/notification", accountController.notification)
router.get("/setting/orders-history", accountController.ordersHistory)
router.post("/login", accountController.loginPost)
router.post("/register", accountController.registerPost)
router.get("/forgot-password", accountController.forgotPassword)
router.post("/forgot-password", accountController.forgotPasswordPost)
router.get("/otp-password", accountController.otpPassword)
router.post("/otp-password", accountController.otpPasswordPost)
router.get("/resetpass", accountController.resetPass)
module.exports = router
