const router = require("express").Router()
const homeRouters = require("./home.router")
const aboutRouters = require("./about.router")
const newsRouters = require("./news.router")
const contactRouter = require("./contact.router")
const settingRouters = require("./setting.router")
const productRouters = require("./products.router")
const cartRouters = require("./cart.router")
const accountRouters = require("./account.router")
router.use("/", homeRouters)
router.use("/about", aboutRouters)  
router.use("/account", accountRouters)  
router.use("/news", newsRouters)
router.use("/contact", contactRouter)
router.use("/setting", settingRouters)
router.use("/products", productRouters)
router.use("/cart", cartRouters)
module.exports = router 